version: 0.0
os: linux
files:
  - source: /
    destination: /data/app/SLA_NESTJS_CLOUD
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
    AfterInstall:
       - location: scripts/stop-containers.sh
         timeout: 300
         runas: root
    ApplicationStart:
       - location: scripts/start-containers.sh
         timeout: 300
         runas: root