version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5434:5432
    networks:
      - sla

networks:
  sla:
